-- 1. 확장 설치 (PostGIS 좌표 및 범위 연산을 위해 필요)
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. 기존 테이블 정리 (Re-runnable하게 개발할 때 유용)
DROP TABLE IF EXISTS plant_health_logs CASCADE;
DROP TABLE IF EXISTS plant_timelapse CASCADE;
DROP TABLE IF EXISTS plant_diary CASCADE;
DROP TABLE IF EXISTS plant_sensor_log CASCADE;
DROP TABLE IF EXISTS plant_activity_stats CASCADE;
DROP TABLE IF EXISTS plant_activity_log CASCADE;
DROP TABLE IF EXISTS plant_achievement CASCADE;
DROP TABLE IF EXISTS plant CASCADE;
DROP TABLE IF EXISTS ref_plant_species CASCADE;
DROP TABLE IF EXISTS ref_plant_disease CASCADE;
DROP TABLE IF EXISTS ref_achievement CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 3. [Users] 유저 테이블
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_image_url TEXT,
    name              VARCHAR(100),
    email             VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255),
    fcm_token         TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE users IS '유저 데이터 저장';

-- 4. [Ref] 참조 테이블들
CREATE TABLE ref_plant_species (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    image_url       TEXT,
    temp_target     INTEGER,
    temp_range      INT4RANGE,
    humid_target    INTEGER,
    humid_range     INT4RANGE,
    soil_target     INTEGER,
    soil_range      INT4RANGE,
    light_intensity INTEGER
);
COMMENT ON TABLE ref_plant_species IS '식물들을 키우기 위해 알아야 할 정보들';

CREATE TABLE ref_achievement (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100),
    icon         TEXT,
    description  TEXT,
    action_type  VARCHAR(50),
    action_count INTEGER,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE ref_achievement IS '도전과제들';

CREATE TABLE ref_plant_disease (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100),
    symptoms   TEXT,
    cure_desc  TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE ref_plant_disease IS '식물 진단 데이터';
COMMENT ON COLUMN ref_plant_disease.name IS '병명';
COMMENT ON COLUMN ref_plant_disease.symptoms IS '증상설명';
COMMENT ON COLUMN ref_plant_disease.cure_desc IS '치료방법';

-- 5. [Plant] 메인 식물 테이블
CREATE TABLE plant (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ref_plant_species_id BIGINT NOT NULL REFERENCES ref_plant_species(id),
    profile_image_url    TEXT,
    is_active            BOOLEAN DEFAULT TRUE,
    health_status        VARCHAR(50),
    signed_at            TIMESTAMPTZ,
    love_temperature     INTEGER NOT NULL DEFAULT 0,
    station_point        GEOMETRY(POINT, 4326), -- WGS84 좌표계 명시
    nickname             VARCHAR(50),
    started_at           TIMESTAMPTZ,
    ended_at             TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant IS '유저별 반려 식물 정보';
COMMENT ON COLUMN plant.nickname IS '식물 애칭';
COMMENT ON COLUMN plant.started_at IS '만난지';
COMMENT ON COLUMN plant.ended_at IS '죽은지...ㅠ';

-- 6. [Logs & Child Tables] 로그 및 하위 테이블
CREATE TABLE plant_sensor_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id      BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    temperature   NUMERIC(5, 2),
    humidity      NUMERIC(5, 2),
    soil_moisture NUMERIC(5, 2),
    light_level   NUMERIC(7, 2),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_sensor_log IS '식물 센서 데이터 로그';

CREATE TABLE plant_diary (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id   BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    title      VARCHAR(200),
    content    TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_diary IS '식물 성장 일기';

CREATE TABLE plant_activity_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id   BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    type       VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_activity_log IS '[user-plant] 상호작용 로그들';

CREATE TABLE plant_activity_stats (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id      BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    activity_type VARCHAR(50),
    total_count   INTEGER DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_activity_stats IS '[user-plant] 상호작용 총합';

CREATE TABLE plant_achievement (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id           BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    ref_achievement_id BIGINT NOT NULL REFERENCES ref_achievement(id),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_achievement IS '유저가 이 식물과 달성한 도전과제들';

CREATE TABLE plant_timelapse (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id   BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    image_url  TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_timelapse IS '식물 타임랩스 사진들 저장소';

CREATE TABLE plant_health_logs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_timelapse_id   BIGINT NOT NULL REFERENCES plant_timelapse(id) ON DELETE CASCADE,
    ref_plant_disease_id BIGINT NOT NULL REFERENCES ref_plant_disease(id),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_health_logs IS '식물에게 관측된 질병들';

-- 7. 인덱스 생성 (성능 최적화)
CREATE INDEX idx_users_email ON users (email ASC);
CREATE INDEX idx_plant_users_id ON plant (users_id ASC);
CREATE INDEX idx_plant_sensor_log_composite ON plant_sensor_log (plant_id ASC, created_at DESC);
CREATE INDEX idx_plant_diary_plant_id ON plant_diary (plant_id ASC, created_at DESC);
CREATE INDEX idx_plant_activity_log_plant_id ON plant_activity_log (plant_id ASC, created_at DESC);
CREATE INDEX idx_plant_timelapse_plant_id ON plant_timelapse (plant_id ASC);


-- 8. [Logs] 식물 센서 데이터 로그 (시간대별 기록)
CREATE TABLE plant_sensor_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id      BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    temperature   NUMERIC(5, 2), -- 온도 (예: 25.45)
    humidity      NUMERIC(5, 2), -- 습도 (예: 60.10)
    soil_moisture NUMERIC(5, 2), -- 토양 습도
    light_level   NUMERIC(7, 2), -- 조도 (Lux 단위 고려)
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE plant_sensor_log IS '식물별 시간대별 센서 측정치 기록';
COMMENT ON COLUMN plant_sensor_log.temperature IS '섭씨 온도(°C)';
COMMENT ON COLUMN plant_sensor_log.humidity IS '대기 습도(%)';
COMMENT ON COLUMN plant_sensor_log.soil_moisture IS '토양 수분 함량(%)';
COMMENT ON COLUMN plant_sensor_log.light_level IS '조도(Lux)';

-- 성능을 위한 인덱스 생성
-- 특정 식물의 최신 데이터를 조회하는 경우가 많으므로 복합 인덱스 권장
CREATE INDEX idx_plant_sensor_log_plant_time ON plant_sensor_log (plant_id ASC, created_at DESC);

-- 더미 !! --


-- 트랜잭션 시작 (모두 성공하거나 모두 실패하도록)
BEGIN;

-- 1. [Users] 유저 생성 (초보, 고수, 방치형 유저)
INSERT INTO users (name, email, password, fcm_token) VALUES 
('식물초보_김싸피', 'ssafy@test.com', 'hashed_pw_1', 'fcm_token_1'),
('프로식집사_이농부', 'farmer@test.com', 'hashed_pw_2', 'fcm_token_2'),
('바쁜현대인_박방치', 'busy@test.com', 'hashed_pw_3', 'fcm_token_3');


-- 2. [Ref] 식물 종 정보 (스마트팜 인기 작물 & 반려식물)
-- Range 타입: [min, max) -> min 이상, max 미만
INSERT INTO ref_plant_species (name, image_url, temp_target, temp_range, humid_target, humid_range, soil_target, soil_range, light_intensity) VALUES 
('몬스테라 델리시오사', 'https://example.com/monstera.png', 
 23, '[18, 30)', 60, '[40, 70)', 50, '[30, 70)', 800),
('방울토마토', 'https://example.com/tomato.png', 
 25, '[20, 30)', 70, '[60, 80)', 60, '[50, 80)', 1500),
('스위트 바질', 'https://example.com/basil.png', 
 23, '[15, 28)', 55, '[40, 60)', 40, '[30, 60)', 1000);


-- 3. [Ref] 질병 정보 (현실적인 병해충)
INSERT INTO ref_plant_disease (name, symptoms, cure_desc) VALUES 
('뿌리파리', '날벌레가 흙 주변을 날아다니고 뿌리 발육이 저하됨', '과습을 피하고 끈끈이 트랩을 설치하거나 빅카드 농약을 희석해 관주합니다.'),
('흰가루병', '잎 표면에 밀가루를 뿌린 듯한 흰색 반점이 생김', '통풍이 잘 되는 곳으로 옮기고 난황유나 살균제를 살포합니다.'),
('잎마름병', '잎 끝이 갈색으로 타들어가며 마름', '공중 습도를 높여주고 직사광선을 피해야 합니다.');


-- 4. [Ref] 도전과제 (게이미피케이션)
INSERT INTO ref_achievement (name, icon, description, action_type, action_count) VALUES 
('설레는 첫 만남', '🌱', '첫 반려 식물을 등록했습니다.', 'REGISTER', 1),
('물주기 장인', '🚿', '물주기 100회를 달성했습니다!', 'WATER', 100),
('식물 수다쟁이', '💬', '식물에게 50번 말을 걸었습니다.', 'TALK', 50),
('초록별의 추억', '⭐', '아쉽지만 식물을 떠나보냈습니다.', 'DEATH', 1);


-- 5. [Plant] 내 식물 등록 (다양한 시나리오)

-- 시나리오 A: 김싸피의 건강한 몬스테라 (서울 역삼동 위치)
INSERT INTO plant (users_id, ref_plant_species_id, nickname, is_active, health_status, love_temperature, station_point, started_at) VALUES 
(1, 1, '몬몬이', TRUE, 'HEALTHY', 75, ST_SetSRID(ST_MakePoint(127.039603, 37.501281), 4326), NOW() - INTERVAL '30 days');

-- 시나리오 B: 이농부의 갓 심은 토마토 (경기도 성남 위치)
INSERT INTO plant (users_id, ref_plant_species_id, nickname, is_active, health_status, love_temperature, station_point, started_at) VALUES 
(2, 2, '멋쟁이토마토', TRUE, 'HEALTHY', 20, ST_SetSRID(ST_MakePoint(127.111489, 37.394726), 4326), NOW() - INTERVAL '2 days');

-- 시나리오 C: 박방치의 죽어가는 바질 (관리가 안됨)
INSERT INTO plant (users_id, ref_plant_species_id, nickname, is_active, health_status, love_temperature, station_point, started_at) VALUES 
(3, 3, '바질페스토', TRUE, 'SICK', 10, ST_SetSRID(ST_MakePoint(127.027619, 37.497942), 4326), NOW() - INTERVAL '60 days');


-- 6. [Plant Diary] 성장 일기 (감성적인 텍스트)
INSERT INTO plant_diary (plant_id, title, content, created_at) VALUES 
(1, '우리집에 온 걸 환영해', '생각보다 잎이 정말 크다. 찢어진 잎이 나올 때까지 잘 키워봐야지.', NOW() - INTERVAL '29 days'),
(1, '새 순이 돋았다!', '오늘 아침에 보니 돌돌 말린 연두색 잎이 빼꼼 나왔다. 너무 귀여워.', NOW() - INTERVAL '15 days'),
(3, '왜 시들지...', '물도 줬는데 잎이 자꾸 검게 변한다. 햇빛이 부족한가?', NOW() - INTERVAL '10 days');


-- 7. [Sensor Log] 센서 데이터 시뮬레이션 (차트 테스트용)
-- 몬몬이(ID:1)의 최근 데이터: 낮에는 온도가 높고 밤에는 낮아지는 패턴

-- 6시간 전 (아침)
INSERT INTO plant_sensor_log (plant_id, temperature, humidity, soil_moisture, light_level, created_at) VALUES 
(1, 22.5, 65.0, 50.0, 300.0, NOW() - INTERVAL '6 hours');

-- 4시간 전 (점심 - 온도 상승, 조도 상승, 습도 하락)
INSERT INTO plant_sensor_log (plant_id, temperature, humidity, soil_moisture, light_level, created_at) VALUES 
(1, 26.8, 55.0, 48.0, 1200.0, NOW() - INTERVAL '4 hours');

-- 2시간 전 (오후)
INSERT INTO plant_sensor_log (plant_id, temperature, humidity, soil_moisture, light_level, created_at) VALUES 
(1, 25.0, 58.0, 46.0, 900.0, NOW() - INTERVAL '2 hours');

-- 현재 (저녁 - 온도 하강)
INSERT INTO plant_sensor_log (plant_id, temperature, humidity, soil_moisture, light_level, created_at) VALUES 
(1, 23.0, 62.0, 45.0, 100.0, NOW());


-- 8. [Activity Log & Stats] 활동 로그 및 통계
INSERT INTO plant_activity_log (plant_id, type, created_at) VALUES 
(1, 'WATER', NOW() - INTERVAL '5 days'),
(1, 'COMMUNION', NOW() - INTERVAL '3 days'), -- 교감하기
(1, 'WATER', NOW() - INTERVAL '1 day');

INSERT INTO plant_activity_stats (plant_id, activity_type, total_count) VALUES 
(1, 'WATER', 2),
(1, 'COMMUNION', 1);


-- 9. [Timelapse & Health] 타임랩스 및 질병 진단 기록
INSERT INTO plant_timelapse (plant_id, image_url, created_at) VALUES 
(3, 'https://example.com/sick_basil_day50.jpg', NOW() - INTERVAL '5 days');

-- 박방치의 바질(ID:3)에서 잎마름병(ID:3)이 발견됨
INSERT INTO plant_health_logs (plant_timelapse_id, ref_plant_disease_id, created_at) VALUES 
(1, 3, NOW() - INTERVAL '5 days');


-- 10. [Achievement] 도전과제 달성
-- 김싸피는 '첫 만남' 도전과제를 깼음
INSERT INTO plant_achievement (plant_id, ref_achievement_id) VALUES 
(1, 1);

COMMIT;