-- 1. 확장 설치 (PostGIS 좌표 및 범위 연산을 위해 필요)
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. ENUM 정의 (타입 안전성 확보)
-- 식물 행동 타입 (데이터 일관성을 위해 소문자로 통일)
DROP TYPE IF EXISTS plant_action_type CASCADE;
CREATE TYPE plant_action_type AS ENUM ('petting', 'watering', 'praising', 'talking', 'diary');

-- 2. 기존 테이블 정리 (Re-runnable하게 개발할 때 유용)
DROP TABLE IF EXISTS plant_health_logs CASCADE;
DROP TABLE IF EXISTS plant_timelapse CASCADE;
DROP TABLE IF EXISTS plant_diary CASCADE;
DROP TABLE IF EXISTS plant_sensor_log CASCADE;
DROP TABLE IF EXISTS plant_activity_counts CASCADE;
DROP TABLE IF EXISTS plant_activity_log CASCADE;
DROP TABLE IF EXISTS plant_achievement CASCADE;
DROP TABLE IF EXISTS plant CASCADE;
DROP TABLE IF EXISTS ref_plant_species CASCADE;
DROP TABLE IF EXISTS ref_plant_disease CASCADE;
DROP TABLE IF EXISTS ref_achievement CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 3. [Users] 유저 테이블
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255),
    name              VARCHAR(100),
    profile_image_url TEXT,
    fcm_token         TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted        BOOLEAN NOT NULL DEFAULT FALSE
);
COMMENT ON TABLE users IS '유저 데이터 저장';

-- 4. [Ref] 참조 테이블들
CREATE TABLE ref_plant_species (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100),
    image_url       TEXT,
    temp_target     INTEGER,
    temp_range      INT4RANGE,
    humid_target    INTEGER,
    humid_range     INT4RANGE,
    soil_target     INTEGER,
    soil_range      INT4RANGE,
    illuminance     INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE ref_plant_species IS '식물들을 키우기 위해 알아야 할 정보들';

CREATE TABLE ref_achievement (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100),
    description  TEXT,
    icon_url     TEXT,
    action_type  plant_action_type,
    required_count INTEGER,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE ref_achievement IS '도전과제들';

CREATE TABLE ref_plant_disease (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100),
    symptoms   TEXT,
    solution   TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE ref_plant_disease IS '식물 진단 데이터';
COMMENT ON COLUMN ref_plant_disease.name IS '병명';
COMMENT ON COLUMN ref_plant_disease.symptoms IS '증상설명';
COMMENT ON COLUMN ref_plant_disease.solution IS '치료방법';

-- 5. [Plant] 메인 식물 테이블
CREATE TABLE plant (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ref_plant_species_id BIGINT NOT NULL REFERENCES ref_plant_species(id),
    nickname             VARCHAR(50),
    profile_image_url    TEXT,
    health_status        VARCHAR(50),
    health_checked_at    TIMESTAMPTZ,
    love_temperature     INTEGER NOT NULL DEFAULT 0,
    is_active            BOOLEAN DEFAULT TRUE,
    station_point        GEOMETRY(POINT, 0), -- WGS84 좌표계 명시
    started_at           TIMESTAMPTZ,
    ended_at             TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant IS '유저별 반려 식물 정보';
COMMENT ON COLUMN plant.nickname IS '식물 애칭';
COMMENT ON COLUMN plant.started_at IS '만난지';
COMMENT ON COLUMN plant.ended_at IS '죽은지...ㅠ';

CREATE TABLE plant_diary (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id    BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    content     TEXT,
    image_url   TEXT,                                          -- 업로드된 이미지 경로
    happened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 실제 사건이 일어난 시간 (달력 표시용)
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 수정한 시간
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP  -- DB에 데이터가 생성된 시간 (시스템용)
);

COMMENT ON TABLE plant_diary IS '식물 성장 일기';
COMMENT ON COLUMN plant_diary.happened_at IS '사용자가 선택한 일기 날짜 (달력 기준)';
COMMENT ON COLUMN plant_diary.created_at IS '실제로 기록을 저장한 시스템 시간';

-- 인덱스 추가 (달력 조회 성능 최적화)
-- 특정 식물의 특정 기간(월별) 일기를 조회할 때 happened_at을 기준으로 정렬/필터링하므로 인덱스가 중요합니다.
CREATE INDEX idx_plant_diary_happened_at ON plant_diary (plant_id ASC, happened_at DESC);

CREATE TABLE plant_activity_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id   BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    type       plant_action_type NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_activity_log IS '[user-plant] 상호작용 로그들';

CREATE TABLE plant_activity_counts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id      BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    activity_type plant_action_type NOT NULL,
    total_count   INTEGER DEFAULT 0,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(plant_id, activity_type)
);
COMMENT ON TABLE plant_activity_counts IS '[user-plant] 상호작용 총합';

CREATE TABLE plant_achievement (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id           BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    ref_achievement_id BIGINT NOT NULL REFERENCES ref_achievement(id),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_achievement IS '유저가 이 식물과 달성한 도전과제들';

CREATE TABLE plant_timelapse (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id   BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    image_url  TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_timelapse IS '식물 타임랩스 사진들 저장소';

CREATE TABLE plant_health_logs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_timelapse_id   BIGINT NOT NULL REFERENCES plant_timelapse(id) ON DELETE CASCADE,
    ref_plant_disease_id BIGINT NOT NULL REFERENCES ref_plant_disease(id),
    confidence           NUMERIC(5,2), -- AI 진단 신뢰도
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_health_logs IS '식물에게 관측된 질병들';

-- 7. 인덱스 생성 (성능 최적화)
CREATE INDEX idx_users_email ON users (email ASC);
CREATE INDEX idx_plant_users_id ON plant (users_id ASC);
-- (plant_sensor_log 인덱스는 테이블 정의 이후에 생성됨)
CREATE INDEX idx_plant_diary_plant_id ON plant_diary (plant_id ASC, created_at DESC);
CREATE INDEX idx_plant_activity_log_plant_id ON plant_activity_log (plant_id ASC, created_at DESC);
CREATE INDEX idx_plant_timelapse_plant_id ON plant_timelapse (plant_id ASC);


-- 8. [Logs] 식물 센서 데이터 로그 (시간대별 기록)
CREATE TABLE plant_sensor_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id      BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    temperature   NUMERIC(5, 2), -- 온도 (예: 25.45)
    humidity      NUMERIC(5, 2), -- 습도 (예: 60.10)
    soil_moisture NUMERIC(5, 2), -- 토양 습도
    illuminance   NUMERIC(7, 2), -- 조도 (Lux 단위 고려)
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE plant_sensor_log IS '식물별 시간대별 센서 측정치 기록';
COMMENT ON COLUMN plant_sensor_log.temperature IS '섭씨 온도(°C)';
COMMENT ON COLUMN plant_sensor_log.humidity IS '대기 습도(%)';
COMMENT ON COLUMN plant_sensor_log.soil_moisture IS '토양 수분 함량(%)';
COMMENT ON COLUMN plant_sensor_log.illuminance IS '조도(Lux)';

-- 성능을 위한 인덱스 생성
-- 특정 식물의 최신 데이터를 조회하는 경우가 많으므로 복합 인덱스 권장
CREATE INDEX idx_plant_sensor_log_plant_time ON plant_sensor_log (plant_id ASC, created_at DESC);
CREATE INDEX idx_plant_sensor_log_composite ON plant_sensor_log (plant_id ASC, created_at DESC);