-- 1. PostGIS 확장 설치 (좌표 데이터를 위해 필요)
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. 기존 테이블 정리 (Re-runnable하도록 설정)
DROP TABLE IF EXISTS plant_health_logs CASCADE;
DROP TABLE IF EXISTS plant_timelapse CASCADE;
DROP TABLE IF EXISTS plant_diary CASCADE;
DROP TABLE IF EXISTS plant_activity_stats CASCADE;
DROP TABLE IF EXISTS plant_activity_log CASCADE;
DROP TABLE IF EXISTS plant_achievement CASCADE;
DROP TABLE IF EXISTS plant CASCADE;
DROP TABLE IF EXISTS ref_plant_species CASCADE;
DROP TABLE IF EXISTS ref_plant_disease CASCADE;
DROP TABLE IF EXISTS ref_achievement CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 3. 테이블 생성 (의존성 없는 테이블 먼저 생성)

-- [Users] 유저 테이블
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_image_url TEXT,
    name              VARCHAR(100),
    email             VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255),
    fcm_token         TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE users IS '유저 데이터 저장';

-- [Ref] 식물 종 정보
CREATE TABLE ref_plant_species (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    image_url       TEXT,
    temp_target     INTEGER,
    temp_range      INT4RANGE, -- PostgreSQL 전용 Range 타입
    humid_target    INTEGER,
    humid_range     INT4RANGE,
    soil_target     INTEGER,
    soil_range      INT4RANGE,
    light_intensity INTEGER
);
COMMENT ON TABLE ref_plant_species IS '식물들을 키우기 위해 알아야 할 정보들';

-- [Ref] 질병 정보
CREATE TABLE ref_plant_disease (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100),
    symptoms   TEXT,
    cure_desc  TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON COLUMN ref_plant_disease.name IS '병명';
COMMENT ON COLUMN ref_plant_disease.symptoms IS '증상설명';
COMMENT ON COLUMN ref_plant_disease.cure_desc IS '치료방법';

-- [Ref] 업적/도전과제 정보
CREATE TABLE ref_achievement (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100),
    icon         TEXT,
    description  TEXT,
    action_type  VARCHAR(50),
    action_count INTEGER,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE ref_achievement IS '도전과제들';


-- 4. 메인 테이블 생성 (Foreign Key 의존성 존재)

-- [Plant] 개별 식물 정보
CREATE TABLE plant (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id             BIGINT NOT NULL REFERENCES users(id),
    ref_plant_species_id BIGINT NOT NULL REFERENCES ref_plant_species(id),
    profile_image_url    TEXT,
    is_active            BOOLEAN DEFAULT TRUE,
    health_status        VARCHAR(50),
    signed_at            TIMESTAMPTZ,
    love_temperature     INTEGER NOT NULL DEFAULT 0,
    station_point        GEOMETRY(POINT, 4326), -- PostGIS 좌표계 (WGS84)
    nickname             VARCHAR(50),
    started_at           TIMESTAMPTZ,
    ended_at             TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON COLUMN plant.nickname IS '식물 애칭';
COMMENT ON COLUMN plant.started_at IS '만난지';
COMMENT ON COLUMN plant.ended_at IS '죽은지...ㅠ';

-- [Logs & Child Tables]

CREATE TABLE plant_achievement (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id           BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    ref_achievement_id BIGINT NOT NULL REFERENCES ref_achievement(id),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_achievement IS '유저가 이 식물과 달성한 도전과제들';

CREATE TABLE plant_activity_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id   BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    type       VARCHAR(50), -- 예: 'WATER', 'LIGHT', 'TALK'
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_activity_log IS '[user-plant] 상호작용 로그들';

CREATE TABLE plant_activity_stats (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id      BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    activity_type VARCHAR(50),
    total_count   INTEGER DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_activity_stats IS '[user-plant] 상호작용 총합';

CREATE TABLE plant_diary (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id   BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    title      VARCHAR(200),
    content    TEXT,
    image_url  TEXT,
    recorded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_diary IS '식물 성장 일기';

CREATE TABLE plant_timelapse (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id   BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    image_url  TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_timelapse IS '식물 타임랩스 사진들 저장소';

CREATE TABLE plant_health_logs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_timelapse_id   BIGINT NOT NULL REFERENCES plant_timelapse(id) ON DELETE CASCADE,
    ref_plant_disease_id BIGINT NOT NULL REFERENCES ref_plant_disease(id),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE plant_health_logs IS '식물에게 관측된 질병들';


-- 5. 인덱스 생성 (성능 최적화)
CREATE INDEX idx_users_email ON users (email ASC);
CREATE INDEX idx_plant_users_id ON plant (users_id ASC);
CREATE INDEX idx_plant_ref_species_id ON plant (ref_plant_species_id ASC);
CREATE INDEX idx_plant_activity_log_created_at ON plant_activity_log (created_at DESC);
CREATE INDEX idx_plant_timelapse_plant_id ON plant_timelapse (plant_id ASC);


-- 6. 더미 데이터 삽입 (Dummy Data Injection)

-- 유저 생성
INSERT INTO users (name, email, password, fcm_token) VALUES 
('김식물', 'farmer@test.com', 'hashed_password_123', 'fcm_token_abc123'),
('이농부', 'lee@test.com', 'hashed_password_456', 'fcm_token_xyz789');

-- 식물 종(Species) 정보 (스마트팜 인기 작물)
INSERT INTO ref_plant_species (name, temp_target, temp_range, humid_target, humid_range, soil_target, soil_range, light_intensity) VALUES 
('몬스테라', 24, '[18, 30)', 60, '[40, 70)', 50, '[30, 70)', 800),
('방울토마토', 25, '[20, 30)', 70, '[60, 80)', 60, '[50, 80)', 1500),
('바질', 23, '[15, 28)', 55, '[40, 60)', 40, '[30, 60)', 1000);

-- 질병 정보
INSERT INTO ref_plant_disease (name, symptoms, cure_desc) VALUES 
('뿌리파리', '날벌레가 날아다니고 뿌리를 갉아먹음', '과습을 피하고 끈끈이 트랩 설치'),
('흰가루병', '잎에 밀가루를 뿌린 듯한 흰 반점', '난황유 살포 및 통풍 개선');

-- 도전과제
INSERT INTO ref_achievement (name, description, action_type, action_count) VALUES 
('첫 만남', '식물을 처음 등록했습니다.', 'REGISTER', 1),
('물주기 장인', '물주기 100회 달성', 'WATER', 100),
('사랑꾼', '식물에게 50번 말을 걸었습니다.', 'TALK', 50);

-- 내 식물 등록 (PostGIS 좌표 포함)
INSERT INTO plant (users_id, ref_plant_species_id, nickname, is_active, love_temperature, station_point, started_at) VALUES 
(1, 1, '몬몬이', TRUE, 36, ST_SetSRID(ST_MakePoint(127.027619, 37.497942), 4326), NOW() - INTERVAL '30 days'),
(1, 2, '토마', TRUE, 15, ST_SetSRID(ST_MakePoint(127.027619, 37.497942), 4326), NOW() - INTERVAL '10 days');

-- 활동 로그
INSERT INTO plant_activity_log (plant_id, type) VALUES 
(1, 'WATER'),
(1, 'LIGHT_ON'),
(1, 'TALK'),
(2, 'WATER');

-- 활동 통계
INSERT INTO plant_activity_stats (plant_id, activity_type, total_count) VALUES 
(1, 'WATER', 15),
(1, 'TALK', 5);

-- 다이어리
INSERT INTO plant_diary (plant_id, title, content) VALUES 
(1, '몬몬이가 집에 온 날', '생각보다 잎이 크다. 잘 키워봐야지.'),
(1, '새 잎이 돋았다', '돌돌 말린 잎이 귀엽다.');

-- 타임랩스 및 질병 로그
INSERT INTO plant_timelapse (plant_id, image_url) VALUES 
(1, 'https://s3.aws.com/bucket/plant1_day1.jpg'),
(1, 'https://s3.aws.com/bucket/plant1_day30.jpg');

INSERT INTO plant_health_logs (plant_timelapse_id, ref_plant_disease_id) VALUES 
(2, 1); -- 30일차 사진에서 뿌리파리 의심 증상 발견

-- 도전과제 달성
INSERT INTO plant_achievement (plant_id, ref_achievement_id) VALUES 
(1, 1);