# location / {...}  밑에 붙여주세요
        location /mqtt {
                proxy_pass http://127.0.0.1:9001; # Mosquitto WebSocket 포트
                proxy_http_version 1.1;

                # WebSocket을 위한 핵심 헤더 설정
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_read_timeout 86400; # 연결 유지를 위해 타임아웃을 길게 설정 (24시간)
        }