slam_toolbox:
  ros__parameters:

    # 1. 프레임 설정 (이게 틀리면 맵 안 나옴)
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # 2. SLAM 동작 모드
    mode: mapping
    map_file_name: test_map
    map_start_pose: [0.0, 0.0, 0.0]

    # 3. 지도 처리 속도 및 정밀도
    map_resolution: 0.05
    map_publish_period: 2.0  # 지도를 5초마다 갱신 (너무 빠르면 부하 걸림)
    transform_publish_period: 0.02
    min_laser_range: 0.1
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # 4. 스캔 매칭 (위치 추정)
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.4
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # 5. 상관관계 (Correction)
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # 6. 루프 클로징 (지도 수정)
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # 7. 스캔 처리
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
