version: '3.8'
services:
  # 1. 메인 데이터베이스
  db:
    image: postgis/postgis:15-3.3
    container_name: farmily-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: farmily_db
      POSTGRES_USER: ssafy
      POSTGRES_PASSWORD: ssafy
      TZ: Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis
  redis:
    image: redis:alpine
    container_name: farmily-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
