spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farmily_db

    username: ssafy
    password: ssafy
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    # DB 스키마 자동 관리 (update: 기존 데이터 유지하면서 변경사항만 반영)
    hibernate:
      ddl-auto: update

    # 실행되는 SQL 눈으로 확인하기 (디버깅용)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # (선택) 파일 업로드 용량 제한 늘리기 (이미지 업로드 대비)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB